SERVER:
  SENSOR_LOCATION_NAME: "SERVER"
  BUCKET_NAME: "Server Room Control"
  BUCKET_KEY: "rt0129"

TEMPERATURE_SERVER:
  BUKET_NAME: "Temperature Server Contrl"
  MINUTES_BETWEEN_READS: 0.5
  METRICS_UNIT: True

TEMPERATURE_SENSOR_01:
  SENSOR_NAME: "DHT22_01"
  PORT: 4

TEMPERATURE_SENSOR_02:
  SENSOR_NAME: "DHT22_02"
  PORT: 5

VOLTAGE_SERVER:
  BUKET_NAME: "Voltage Server Control"

VOLTAGE_SENSOR_01:
  SENSOR_NAME: "SCT013"
  PORT: 1000
