SERVER:
  SENSOR_LOCATION_NAME: "SERVER"
  BUCKET_NAME: "Server Room Control"
  BUCKET_KEY: "rt0129"
  DEBUG: True

TEMPERATURE_SERVER:
  NAME: "Temperature Server Control"
  MINUTES_BETWEEN_READS: 0.05
  METRICS_UNIT: True

SENSORS:
  TEMPERATURE_SENSOR: [{ NAME: "DHT22_01", PORT: 4, DEBUG: False}, { NAME: "DHT22_02", PORT: 3, DEBUG: False}]

VOLTAGE_SERVER:
  BUKET_NAME: "Voltage Server Control"

VOLTAGE_SENSOR_01:
  SENSOR_NAME: "SCT013"
  PORT: 1000

LCD:
  PIN_RS: 37
  PIN_E: 35
  PINS_DATA: [33, 31, 29, 23]

DB:
  USER: "rv"
  PASSWORD: "narsil"
  HOST: "localhost"
  PORT: 3306
  DBNAME: "accontrol"

GPIOS:
  TEMPERATURE_SENSOR_ALERT_PIN: 12
  TEMPERATURE_WARNING_ALERT_PIN: 16
  TEMPERATURE_DANGER_ALERT_PIN: 18
  Ok_ALERT: 22
  VOLTAGE_ALERT_PIN: 24
  ALARM_ALERT_PIN: 26
