SERVER:
  SENSOR_LOCATION_NAME: "SERVER"
  BUCKET_NAME: "Server Room Control"
  BUCKET_KEY: "rt0129"
  DEBUG: True

TEMPERATURE_SERVER:
  NAME: "Temperature Server Control"
  MINUTES_BETWEEN_READS: 0.05
  METRICS_UNIT: True

SENSORS:
  TEMPERATURE_SENSOR: [{ NAME: "DHT22_01", PORT: 17, DEBUG: False}, { NAME: "DHT22_02", PORT: 4, DEBUG: False}]

VOLTAGE_SERVER:
  BUKET_NAME: "Voltage Server Control"

VOLTAGE_SENSOR_01:
  SENSOR_NAME: "SCT013"
  PORT: 1000

LCD:
  # PIN_RS: 37
  # PIN_E: 35
  # PINS_DATA: [33, 31, 29, 23]
  ADDRESS: 0x27
  LCDMODE: "i2c"
  COLS: 20
  ROWS: 4
  CHARMAP: "A00"
  I2C_EXPANDER: "PCF8574"
  PORT: 1

DB:
  USER: "rv"
  PASSWORD: "narsil"
  HOST: "localhost"
  PORT: 3306
  DBNAME: "accontrol"

GPIOS:
  # 18 GPIO.BCM - 12 GPIO.BOARD
  # 23 GPIO.BCM - 16 GPIO.BOARD
  # 24 GPIO.BCM - 18 GPIO.BOARD
  # 25 GPIO.BCM - 22 GPIO.BOARD
  # 8  GPIO.BCM - 24 GPIO.BOARD
  # 7  GPIO.BCM - 26 GPIO.BOARD
  TEMPERATURE_SENSOR_ALERT_PIN: 18 
  TEMPERATURE_WARNING_ALERT_PIN: 23
  TEMPERATURE_DANGER_ALERT_PIN: 24 
  Ok_ALERT: 25 
  VOLTAGE_ALERT_PIN: 8
  ALARM_ALERT_PIN: 7

TELEGRAM:
  TOKEN: 6374080755:AAGqpWBMGfqSn6WvUGY9miLem_0jy3Peef8
  CHATGROUPID: -4079618753
  SENSOR_PROBLEM_MESSAGE: "We have some problems with one or more sensors."
  TEMPERATURE_WARNING_MESSAGE: "Maybe you must confere the server room, the temperature is rising."
  TEMPERATURE_DANGER_MESSAGE: "Oh my GOD, Run!!! The temperature is big!!!"