
class statusCode:
    OK = 10                         # OK
    SENSOR_OK = 11
    OK_WAINTING = 15                # OK, WAINTING FOR MORE DATA
    TEMPERATURE_SENSOR_ERROR = 20   # TEMPERATURE SENSOR PROBLEM
    VOLTAGE_SENSOR_ERROR = 21       # VOLTAGE SENSOR PROBLEM
    WARNING_TEMPERATURE = 40
    DANGER_TEMPERATURE = 50
    DANGER_VOLTAGE_SENSOR = 51